version: '3.8'
services:
  solr:
    container_name: solr
    image: solr:8.11.0
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - jcg_example_core
volumes:
  data: